[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py init_admin && gunicorn bk_plan.wsgi --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-file -"
restartPolicyType = "on_failure"
